const iconMap = {
    "sunny": "113.png",
    "clear": "113.png",
    "partly cloudy": "116.png",
    "cloudy": "119.png",
    "overcast": "122.png",
    "mist": "143.png",
    "light rain": "176.png",
    "moderate rain": "302.png",
    "heavy rain": "308.png",
    "thunderstorm": "389.png",
    "snow": "227.png",
    "light snow": "179.png",
    "fog": "248.png",
    "freezing fog": "260.png",
    "patchy rain possible": "176.png",
    "patchy rain nearby": "176.png",
    "patchy snow possible": "179.png",
    "patchy sleet possible": "182.png",
    "patchy freezing drizzle possible": "185.png",
    "thundery outbreaks possible": "200.png",
    "blowing snow": "227.png",
    "blizzard": "230.png",
    "freezing drizzle": "281.png",
    "heavy snow": "338.png",
    "ice pellets": "350.png",
    "light drizzle": "353.png",
    "freezing rain": "362.png",
    "heavy freezing drizzle": "365.png",
    "light rain shower": "293.png",
    "moderate or heavy rain shower": "296.png",
    "torrential rain shower": "299.png",
};

export default iconMap;
